SAMPLE_POSTS = [
    {
        "slug": "africas-national-parks-beyond-the-big-five",
        "title": "Africa’s national parks ranked: ten landscapes beyond the Big Five",
        "lead": "A wider view of protected Africa, from Botswana’s salt pans to Gabon’s forest-lined Atlantic shore.",
        "published_at": "2026-09-01",
        "image_blob": "africa-national-parks.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/12cf5f52c69c49e0aa2977424bebda5a.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/africas-national-parks-ranked-ten-landscapes-beyond-the-big-five",
        "story": [
            "Africa’s protected landscapes offer far more than a familiar wildlife checklist. This journey compares ten parks through the character of their land, from mineral-white basins and high plateaus to rainforest meeting ocean.",
            "The selection encourages travellers to notice geology, water, vegetation and remoteness alongside animals. Each park presents a different relationship between habitat and the communities living around it.",
            "The result is an invitation to choose a safari by landscape and season, then travel slowly enough to appreciate the ecosystems that make every sighting possible.",
        ],
    },
    {
        "slug": "ascensor-reina-victoria-valparaiso",
        "title": "Ascensor Reina Victoria: Valparaíso in 40 steep metres",
        "lead": "A tiny funicular turns one of Valparaíso’s sharpest climbs into a memorable piece of everyday transport.",
        "published_at": "2026-08-31",
        "image_blob": "valparaiso-funicular.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/7f91d314e0694435b6ec82b2b94eb5b6.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/ascensor-reina-victoria-valparaiso-in-40-steep-metres",
        "story": [
            "At Calle Elías, rails rise abruptly toward Cerro Alegre. Ascensor Reina Victoria covers only a short distance, yet its steep passage neatly joins the lower city to the hill’s pedestrian lanes.",
            "The ride is part utility and part introduction to Valparaíso’s vertical geography. At the upper station, Paseo Dimalow opens onto colourful streets shaped by port history and immigrant architecture.",
            "Taking the lift reveals how infrastructure can become part of a city’s identity: modest in scale, practical in purpose and inseparable from the experience of moving through the hills.",
        ],
    },
    {
        "slug": "asias-five-exceptional-beaches",
        "title": "Asia’s five most exceptional beaches, ranked",
        "lead": "Five shores compared not only for beauty, but for swimming, access, quiet and the right season to arrive.",
        "published_at": "2026-08-30",
        "image_blob": "asia-beaches.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/2e797b55bbf44d9fafa5dd36f4f0bc5d.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/asias-five-most-exceptional-beaches-ranked",
        "story": [
            "A beautiful photograph tells only part of a beach’s story. This ranking considers what a day there actually feels like, including water conditions, snorkelling, crowds and the effort needed to reach the sand.",
            "Seasonality matters just as much as scenery. Monsoon patterns, visibility and changing seas can transform the same coast, so timing is treated as part of the destination rather than an afterthought.",
            "The five choices reward travellers who match a beach to the experience they want—easy swimming, underwater life, solitude or a dramatic journey to the shore.",
        ],
    },
    {
        "slug": "buenos-aires-at-the-kiosk-window",
        "title": "Buenos Aires at the kiosk window",
        "lead": "A green newspaper kiosk shows how a small street institution can adapt while keeping its neighbourhood rhythm.",
        "published_at": "2026-08-29",
        "image_blob": "buenos-aires-kiosk.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/f508f5bcbb954bea85014d2527a934e3.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/buenos-aires-at-the-kiosk-window",
        "story": [
            "On the corner of Junín and Paraguay, Canillita still presents magazines to the pavement, but coffee now passes through the window too. The expanded offer keeps a traditional kiosk useful to modern foot traffic.",
            "Its appeal lies in the compact exchange between seller, walker and street. Customers pause without fully leaving the flow of the neighbourhood, turning an ordinary errand into a small social ritual.",
            "The kiosk offers a close-up way to read Buenos Aires: through daily habits, improvised adaptation and the enduring value of places designed at walking speed.",
        ],
    },
    {
        "slug": "sao-jose-market-to-recifes-tidal-river",
        "title": "From São José Market to Recife’s tidal river",
        "lead": "An iron market and a short walk to the Capibaribe reveal how trade grew among Recife’s islands and bridges.",
        "published_at": "2026-08-28",
        "image_blob": "recife-market.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/4315e966a8f943a2bd74b9ba05434a33.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/from-sao-jose-market-to-recifes-tidal-river",
        "story": [
            "Mercado de São José is organised around iron columns, enclosed stalls and two linked pavilions. Its structure gives a clear frame to the dense movement of vendors, shoppers and goods.",
            "Outside, the Capibaribe is only a short walk away. The river explains much of central Recife’s form, where islands, quays and bridges have long directed commercial life.",
            "Seen together, market and water turn a city walk into a lesson in geography. The route connects architecture to the tidal system that helped determine where people met and traded.",
        ],
    },
    {
        "slug": "laweyan-batik-still-lives-at-home",
        "title": "In Laweyan, batik still lives at home",
        "lead": "Solo’s historic batik neighbourhood keeps knowledge moving through families, workshops and classrooms.",
        "published_at": "2026-08-27",
        "image_blob": "laweyan-batik.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/d109e352a7ba49d2b43c42706210ff14.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/in-laweyan-batik-still-lives-at-home",
        "story": [
            "In Kampung Batik Laweyan, cloth production remains closely connected to domestic spaces and family businesses. Experienced makers share methods with children, trainees and design students.",
            "Following the process reveals batik as more than a finished pattern. Drawing, wax, dye and repeated handling bring together artistic decisions, patient labour and commercial knowledge.",
            "For visitors, the neighbourhood offers a respectful way to understand living heritage: meeting the people who sustain the craft and seeing how skills are renewed rather than simply preserved.",
        ],
    },
    {
        "slug": "manises-where-clay-marks-the-town",
        "title": "Manises: where clay still marks the town",
        "lead": "Centuries of ceramic work remain visible in a museum, active workshops and the tiled surfaces of everyday streets.",
        "published_at": "2026-08-26",
        "image_blob": "manises-ceramics.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/9751d623e94041a1a4d4851365447ad4.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/manises-where-clay-still-marks-the-town",
        "story": [
            "Casa Ferraro’s tiled façade leads into the Museu de la Ceràmica de Manises, where local objects trace the town’s changing techniques and international reputation across centuries.",
            "The story continues beyond display cases. Workshops, a ceramics school and decorated public spaces show how clay has shaped both employment and the visual language of the town.",
            "Walking Manises links historical craft to present-day practice. Tiles become evidence of trade, technology and inherited expertise rather than decoration alone.",
        ],
    },
    {
        "slug": "sesame-bread-and-knafeh-in-amman",
        "title": "Sesame bread and knafeh in downtown Amman",
        "lead": "A bakery stop places warm ka’ak inside the movement of downtown streets, shops and steep routes home.",
        "published_at": "2026-08-25",
        "image_blob": "amman-bread.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/4d518e12f75b41f2acb9e316aff565f2.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/sesame-bread-and-knafeh-in-downtown-amman",
        "story": [
            "At Salaheddine Bakery, customers choose sesame-coated ka’ak from a wooden bin, split the bread and add fillings at the counter. It is a quick meal built around freshness and routine.",
            "The bakery’s location ties food to downtown Amman’s wider movement. Workers, shoppers and residents stop between traffic-filled streets and climbs toward the surrounding hills.",
            "Paired with the city’s knafeh tradition, the bread offers a route through Amman led by everyday appetite—direct, sociable and closely connected to place.",
        ],
    },
    {
        "slug": "european-railways-as-destinations",
        "title": "Seven European train routes where the railway is the destination",
        "lead": "Seven public rail journeys where bridges, engineering and passing landscapes matter as much as arrival.",
        "published_at": "2026-08-24",
        "image_blob": "europe-railways.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/8f0e2d09a01b4e6d9ce2161b44adf002.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/seven-european-train-routes-where-the-railway-is-the-destination",
        "story": [
            "Some railways turn movement itself into the day’s main experience. These seven routes place passengers beside rock walls, across historic bridges and through landscapes best understood from the track.",
            "The journeys also foreground engineering. Lines built around difficult terrain reveal how tunnels, gradients and viaducts made regular public transport possible in remarkable settings.",
            "Choosing the train makes the space between cities visible. A window seat, an unhurried timetable and attention to the route can turn transit into a richer form of travel.",
        ],
    },
    {
        "slug": "caribbean-islands-beyond-the-resort",
        "title": "The Caribbean’s eight best islands for life beyond the resort",
        "lead": "Eight islands ranked for the culture, nature and distinctive local days found away from resort gates.",
        "published_at": "2026-08-23",
        "image_blob": "caribbean-islands.jpg",
        "image_source": "https://hamba.nl/media/destinations/originals/2026-08/4c626a5b83f442a792e2e02a350002b9.jpg?width=1180&height=664&mode=cover",
        "source_url": "https://hamba.nl/en/magazine/the-caribbeans-eight-best-islands-for-life-beyond-the-resort",
        "story": [
            "This island ranking looks beyond beach quality alone. Nature, culture, town life and individual character all count toward how rewarding a stay can be outside a resort.",
            "Larger islands are judged by the variety of days they offer across coast, interior and urban neighbourhoods. Smaller islands stand out when a strong identity outweighs their limited scale.",
            "The comparison encourages independent exploration and locally rooted choices. The best island is the one whose everyday life remains as compelling as its shoreline.",
        ],
    },
]
